import type { RankDefinition } from "./types";

export const RANK_DEFINITIONS: RankDefinition[] = [
  {
    key: "BEGINNER",
    label: "Başlangıç",
    minimum: 0,
    description: "Film zevkinin ilk sinyalleri toplanıyor.",
    badgeIcon: "🌱",
  },
  {
    key: "VIEWER",
    label: "İzleyici",
    minimum: 30,
    description: "İlk Film DNA profilin oluştu.",
    badgeIcon: "🎬",
  },
  {
    key: "CINEPHILE",
    label: "Sinefil",
    minimum: 100,
    description: "Tür ve dönem tercihlerin belirginleşti.",
    badgeIcon: "🍿",
  },
  {
    key: "CURATOR",
    label: "Küratör",
    minimum: 250,
    description: "Zevk profilin artık daha ince ayrımları yakalıyor.",
    badgeIcon: "🏛️",
  },
  {
    key: "ARCHIVIST",
    label: "Arşivci",
    minimum: 500,
    description: "Geniş bir film kataloğu üzerinden güçlü sinyaller oluştu.",
    badgeIcon: "📜",
  },
  {
    key: "DISTINGUISHED_VIEWER",
    label: "Seçkin İzleyici",
    minimum: 750,
    description: "Film zevkin artık geniş ve belirgin.",
    badgeIcon: "🎖️",
  },
  {
    key: "MASTER_CINEPHILE",
    label: "Usta Sinefil",
    minimum: 1000,
    description: "Film DNA'n oldukça güçlü ve detaylı.",
    badgeIcon: "👑",
  },
  {
    key: "CINEMA_SAGE",
    label: "Sinema Bilgesi",
    minimum: 1250,
    description: "Farklı dönem ve türlerde güçlü bir sinema hafızan var.",
    badgeIcon: "🧠",
  },
  {
    key: "CHIEF_CURATOR",
    label: "Baş Küratör",
    minimum: 1500,
    description: "Zevk profilin çok sayıda film üzerinden ince ayrımlar yapabiliyor.",
    badgeIcon: "🎞️",
  },
  {
    key: "FILM_ARCHAEOLOGIST",
    label: "Film Arkeoloğu",
    minimum: 1750,
    description: "Ana akımın ötesine geçen geniş bir sinema keşif geçmişin var.",
    badgeIcon: "🔎",
  },
  {
    key: "CINEMA_MASTER",
    label: "Sinema Ustası",
    minimum: 2000,
    description: "Film DNA'n son derece detaylı ve derin.",
    badgeIcon: "⭐",
  },
  {
    key: "FILMPRINT_LEGEND",
    label: "Filmprint Legend",
    minimum: 2500,
    description: "Filmprint kataloğunda olağanüstü geniş bir iz bıraktın.",
    badgeIcon: "🏆",
  },
  {
    key: "CINEMA_MEMORY",
    label: "Sinema Hafızası",
    minimum: 3000,
    description: "Geniş sinema tarihi boyunca benzersiz ve derin bir izleme hafızası.",
    badgeIcon: "📼",
  },
  {
    key: "GRAND_ARCHIVIST",
    label: "Büyük Arşivci",
    minimum: 4000,
    description: "Binlerce yapımı kapsayan devasa ve kusursuz bir sinema arşivi.",
    badgeIcon: "🗃️",
  },
  {
    key: "CINEMA_ENCYCLOPEDIA",
    label: "Sinema Ansiklopedisi",
    minimum: 5000,
    description: "Sinema dünyasının tüm dönem ve akımlarına hakim ansiklopedik birikim.",
    badgeIcon: "📖",
  },
  {
    key: "CINEMA_VIRTUOSO",
    label: "Sinema Üstadı",
    minimum: 7500,
    description: "En nadide sanat yapımlarından kült başyapıtlara uzanan virtüöz seviyesinde sinema sezgisi.",
    badgeIcon: "🎭",
  },
  {
    key: "FILMPRINT_ICON",
    label: "Filmprint Efsanesi",
    minimum: 10000,
    description: "Filmprint tarihinde kalıcı ve ikonik bir sinema mirası.",
    badgeIcon: "💎",
  },
  {
    key: "GRAND_CINEPHILE",
    label: "Büyük Sinefil",
    minimum: 15000,
    description: "Sıra dışı derinlikte, dünya sinemasında eşine az rastlanır bir sinefil yolculuğu.",
    badgeIcon: "🌌",
  },
  {
    key: "LIVING_FILM_ARCHIVE",
    label: "Yaşayan Sinema Arşivi",
    minimum: 25000,
    description: "Dünya sinemasının yaşayan ve nefes alan en görkemli canlı arşivi.",
    badgeIcon: "👑",
  },
];
