import type { RankDefinition, TvRankKey } from "./types";


export const RANK_DEFINITIONS: RankDefinition[] = [
  {
    key: "BEGINNER",
    label: "Başlangıç",
    minimum: 0,
    description: "Film zevkinin ilk sinyalleri toplanıyor.",
    badgeIcon: "🌱",
  },
  {
    key: "VIEWER",
    label: "İzleyici",
    minimum: 30,
    description: "İlk Film DNA profilin oluştu.",
    badgeIcon: "🎬",
  },
  {
    key: "CINEPHILE",
    label: "Sinefil",
    minimum: 100,
    description: "Tür ve dönem tercihlerin belirginleşti.",
    badgeIcon: "🍿",
  },
  {
    key: "CURATOR",
    label: "Küratör",
    minimum: 250,
    description: "Zevk profilin artık daha ince ayrımları yakalıyor.",
    badgeIcon: "🏛️",
  },
  {
    key: "ARCHIVIST",
    label: "Arşivci",
    minimum: 500,
    description: "Geniş bir film kataloğu üzerinden güçlü sinyaller oluştu.",
    badgeIcon: "📜",
  },
  {
    key: "DISTINGUISHED_VIEWER",
    label: "Seçkin İzleyici",
    minimum: 750,
    description: "Film zevkin artık geniş ve belirgin.",
    badgeIcon: "🎖️",
  },
  {
    key: "MASTER_CINEPHILE",
    label: "Usta Sinefil",
    minimum: 1000,
    description: "Film DNA'n oldukça güçlü ve detaylı.",
    badgeIcon: "👑",
  },
  {
    key: "CINEMA_SAGE",
    label: "Sinema Bilgesi",
    minimum: 1250,
    description: "Farklı dönem ve türlerde güçlü bir sinema hafızan var.",
    badgeIcon: "🧠",
  },
  {
    key: "CHIEF_CURATOR",
    label: "Baş Küratör",
    minimum: 1500,
    description: "Zevk profilin çok sayıda film üzerinden ince ayrımlar yapabiliyor.",
    badgeIcon: "🎞️",
  },
  {
    key: "FILM_ARCHAEOLOGIST",
    label: "Film Arkeoloğu",
    minimum: 1750,
    description: "Ana akımın ötesine geçen geniş bir sinema keşif geçmişin var.",
    badgeIcon: "🔎",
  },
  {
    key: "CINEMA_MASTER",
    label: "Sinema Ustası",
    minimum: 2000,
    description: "Film DNA'n son derece detaylı ve derin.",
    badgeIcon: "⭐",
  },
  {
    key: "FILMPRINT_LEGEND",
    label: "Filmprint Legend",
    minimum: 2500,
    description: "Filmprint kataloğunda olağanüstü geniş bir iz bıraktın.",
    badgeIcon: "🏆",
  },
  {
    key: "CINEMA_MEMORY",
    label: "Sinema Hafızası",
    minimum: 3000,
    description: "Geniş sinema tarihi boyunca benzersiz ve derin bir izleme hafızası.",
    badgeIcon: "📼",
  },
  {
    key: "GRAND_ARCHIVIST",
    label: "Büyük Arşivci",
    minimum: 4000,
    description: "Binlerce yapımı kapsayan devasa ve kusursuz bir sinema arşivi.",
    badgeIcon: "🗃️",
  },
  {
    key: "CINEMA_ENCYCLOPEDIA",
    label: "Sinema Ansiklopedisi",
    minimum: 5000,
    description: "Sinema dünyasının tüm dönem ve akımlarına hakim ansiklopedik birikim.",
    badgeIcon: "📖",
  },
  {
    key: "CINEMA_VIRTUOSO",
    label: "Sinema Üstadı",
    minimum: 7500,
    description: "En nadide sanat yapımlarından kült başyapıtlara uzanan virtüöz seviyesinde sinema sezgisi.",
    badgeIcon: "🎭",
  },
  {
    key: "FILMPRINT_ICON",
    label: "Filmprint Efsanesi",
    minimum: 10000,
    description: "Filmprint tarihinde kalıcı ve ikonik bir sinema mirası.",
    badgeIcon: "💎",
  },
  {
    key: "GRAND_CINEPHILE",
    label: "Büyük Sinefil",
    minimum: 15000,
    description: "Sıra dışı derinlikte, dünya sinemasında eşine az rastlanır bir sinefil yolculuğu.",
    badgeIcon: "🌌",
  },
  {
    key: "LIVING_FILM_ARCHIVE",
    label: "Yaşayan Sinema Arşivi",
    minimum: 25000,
    description: "Dünya sinemasının yaşayan ve nefes alan en görkemli canlı arşivi.",
    badgeIcon: "👑",
  },
];

export const TV_RANK_DEFINITIONS: RankDefinition<TvRankKey>[] = [
  {
    key: "TV_PASSENGER",
    label: "Dizi Yolcusu",
    minimum: 0,
    description: "Dizi zevkinin ilk sinyalleri toplanıyor.",
    badgeIcon: "🌱",
  },
  {
    key: "TV_EXPLORER",
    label: "Dizi Kaşifi",
    minimum: 15,
    description: "İlk Dizi DNA profilin oluştu.",
    badgeIcon: "🔍",
  },
  {
    key: "TV_ENTHUSIAST",
    label: "Dizi Meraklısı",
    minimum: 30,
    description: "Dizi format ve tür tercihlerin belirginleşti.",
    badgeIcon: "🍿",
  },
  {
    key: "TV_PASSIONATE",
    label: "Dizi Tutkunu",
    minimum: 50,
    description: "Dizi izleme zevkin belirginleşiyor.",
    badgeIcon: "🎬",
  },
  {
    key: "TV_HUNTER",
    label: "Dizi Avcısı",
    minimum: 100,
    description: "Sezon ve bölüm alışkanlıkların derinleşti.",
    badgeIcon: "🎯",
  },
  {
    key: "TV_CURATOR",
    label: "Dizi Küratörü",
    minimum: 150,
    description: "Zevk profilin daha ince dizi ayrımlarını yakalıyor.",
    badgeIcon: "🏛️",
  },
  {
    key: "TV_EXPERT",
    label: "Dizi Uzmanı",
    minimum: 250,
    description: "Geniş bir dizi kataloğu üzerinden güçlü sinyaller oluştu.",
    badgeIcon: "🎖️",
  },
  {
    key: "TV_ARCHIVIST",
    label: "Dizi Arşivcisi",
    minimum: 400,
    description: "Kapsamlı bir dizi izleme hafızası oluşturdun.",
    badgeIcon: "📜",
  },
  {
    key: "TV_CRITIC",
    label: "Dizi Eleştirmeni",
    minimum: 600,
    description: "Farklı tür ve formatlarda seçkin bir dizi zevkin var.",
    badgeIcon: "🧠",
  },
  {
    key: "TV_MASTER",
    label: "Dizi Ustası",
    minimum: 1000,
    description: "Dizi DNA'n son derece detaylı ve güçlü.",
    badgeIcon: "👑",
  },
  {
    key: "TV_ARCHAEOLOGIST",
    label: "Dizi Arkeoloğu",
    minimum: 1500,
    description: "Popüler dizilerin ötesinde derin keşif birikimi.",
    badgeIcon: "🔎",
  },
  {
    key: "TV_ENCYCLOPEDIA",
    label: "Dizi Ansiklopedisi",
    minimum: 2000,
    description: "Dizi dünyasının tüm dönem ve formatlarına hakim birikim.",
    badgeIcon: "📖",
  },
  {
    key: "GRAND_TV_ARCHIVIST",
    label: "Büyük Dizi Arşivcisi",
    minimum: 3000,
    description: "Binlerce bölümü kapsayan devasa bir dizi arşivi.",
    badgeIcon: "🗃️",
  },
  {
    key: "TV_VIRTUOSO",
    label: "Dizi Üstadı",
    minimum: 5000,
    description: "Kült yapımlardan niş mini dizilere uzanan üstat seviyesi dizi zevki.",
    badgeIcon: "🎭",
  },
  {
    key: "TV_LEGEND",
    label: "Dizi Efsanesi",
    minimum: 7500,
    description: "Dizi dünyasında eşine az rastlanır ikonik bir yolculuk.",
    badgeIcon: "💎",
  },
  {
    key: "LIVING_TV_ARCHIVE",
    label: "Yaşayan Dizi Arşivi",
    minimum: 10000,
    description: "Televizyon ve dizi dünyasının yaşayan ve nefes alan en görkemli canlı arşivi.",
    badgeIcon: "🌌",
  },
];

